<a href="https://colab.research.google.com/github/mamaruru/GitHub/blob/master/AIStudy/T_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
lst = [1, 2, 3];
nlst = lst + lst;
nlst

[1, 2, 3, 1, 2, 3]

In [0]:
import numpy as np


In [0]:
np.add(lst, lst)

array([2, 4, 6])

In [0]:
np.multiply(lst, lst)

array([1, 4, 9])

In [0]:
lst1 = [2, 4, 6, 8, 10]
lst2 = [1, 3, 5, 7, 9]
np.multiply( lst1 , lst2)

array([ 2, 12, 30, 56, 90])

In [0]:
np.divide( lst1 , lst2)

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111])

In [0]:
np.subtract(lst1, lst2)

array([1, 1, 1, 1, 1])